# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      #- id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ["-b", "main"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 19.10b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=88
          - --include='\.pyi?$'
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: tags/3.7.9
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    - id: mypy
      additional_dependencies: [types-requests]
